package com.yshyerp.adm.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @Author: zhoyuhao
 * @Data: 2020-10-30
 * @Description: 货品entity
 */
@TableName("commodity")
public class CommodityEntity implements Serializable {

    private Integer key;

    public Integer getKey() {
        return key;
    }

    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.commodity
     *
     * @mbggenerated
     */

    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.fullname
     *
     * @mbggenerated
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.density
     *
     * @mbggenerated
     */
    private BigDecimal density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_code
     *
     * @mbggenerated
     */
    private String commCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.wx
     *
     * @mbggenerated
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.id
     *
     * @mbggenerated
     */
    @TableId(value = "id",type=IdType.AUTO)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.order1
     *
     * @mbggenerated
     */
    private Integer order1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.flash
     *
     * @mbggenerated
     */
    private BigDecimal flash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.nature
     *
     * @mbggenerated
     */
    private String nature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commodity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.code
     *
     * @return the value of commodity.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.code
     *
     * @param code the value for commodity.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.commodity
     *
     * @return the value of commodity.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.commodity
     *
     * @param commodity the value for commodity.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.fullname
     *
     * @return the value of commodity.fullname
     *
     * @mbggenerated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.fullname
     *
     * @param fullname the value for commodity.fullname
     *
     * @mbggenerated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.cname
     *
     * @return the value of commodity.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.cname
     *
     * @param cname the value for commodity.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.density
     *
     * @return the value of commodity.density
     *
     * @mbggenerated
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.density
     *
     * @param density the value for commodity.density
     *
     * @mbggenerated
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_code
     *
     * @return the value of commodity.comm_code
     *
     * @mbggenerated
     */
    public String getCommCode() {
        return commCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_code
     *
     * @param commCode the value for commodity.comm_code
     *
     * @mbggenerated
     */
    public void setCommCode(String commCode) {
        this.commCode = commCode == null ? null : commCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.d
     *
     * @return the value of commodity.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.d
     *
     * @param d the value for commodity.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.wx
     *
     * @return the value of commodity.wx
     *
     * @mbggenerated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.wx
     *
     * @param wx the value for commodity.wx
     *
     * @mbggenerated
     */
    public void setWx(String wx) {
        this.wx = wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.id
     *
     * @return the value of commodity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.id
     *
     * @param id the value for commodity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.order1
     *
     * @return the value of commodity.order1
     *
     * @mbggenerated
     */
    public Integer getOrder1() {
        return order1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.order1
     *
     * @param order1 the value for commodity.order1
     *
     * @mbggenerated
     */
    public void setOrder1(Integer order1) {
        this.order1 = order1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.flash
     *
     * @return the value of commodity.flash
     *
     * @mbggenerated
     */
    public BigDecimal getFlash() {
        return flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.flash
     *
     * @param flash the value for commodity.flash
     *
     * @mbggenerated
     */
    public void setFlash(BigDecimal flash) {
        this.flash = flash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.nature
     *
     * @return the value of commodity.nature
     *
     * @mbggenerated
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.nature
     *
     * @param nature the value for commodity.nature
     *
     * @mbggenerated
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.type
     *
     * @return the value of commodity.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.type
     *
     * @param type the value for commodity.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}