package com.yshyerp.adm.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;

import java.io.Serializable;
@TableName("cust_email")
public class CusEmail implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.d1_enabled
     *
     * @mbggenerated
     */
    @TableField("d1_enabled")
    private Boolean d1Enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.d_enabled
     *
     * @mbggenerated
     */
    @TableField("d_enabled")
    private Integer dEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.rd_enabled
     *
     * @mbggenerated
     */
    @TableField("rd_enabled")
    private Integer rdEnabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.rd_mail
     *
     * @mbggenerated
     */
    @TableField("rd_mail")
    private String rdMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email1
     *
     * @mbggenerated
     */
    private String email1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email2
     *
     * @mbggenerated
     */
    private String email2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email3
     *
     * @mbggenerated
     */
    private String email3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email4
     *
     * @mbggenerated
     */
    private String email4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email5
     *
     * @mbggenerated
     */
    private String email5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email6
     *
     * @mbggenerated
     */
    private String email6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email7
     *
     * @mbggenerated
     */
    private String email7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cust_email.email8
     *
     * @mbggenerated
     */
    private String email8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cust_email
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.customer
     *
     * @return the value of cust_email.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.customer
     *
     * @param customer the value for cust_email.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.d1_enabled
     *
     * @return the value of cust_email.d1_enabled
     *
     * @mbggenerated
     */
    public Boolean getD1Enabled() {
        return d1Enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.d1_enabled
     *
     * @param d1Enabled the value for cust_email.d1_enabled
     *
     * @mbggenerated
     */
    public void setD1Enabled(Boolean d1Enabled) {
        this.d1Enabled = d1Enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.d_enabled
     *
     * @return the value of cust_email.d_enabled
     *
     * @mbggenerated
     */
    public Integer getdEnabled() {
        return dEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.d_enabled
     *
     * @param dEnabled the value for cust_email.d_enabled
     *
     * @mbggenerated
     */
    public void setdEnabled(Integer dEnabled) {
        this.dEnabled = dEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.rd_enabled
     *
     * @return the value of cust_email.rd_enabled
     *
     * @mbggenerated
     */
    public Integer getRdEnabled() {
        return rdEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.rd_enabled
     *
     * @param rdEnabled the value for cust_email.rd_enabled
     *
     * @mbggenerated
     */
    public void setRdEnabled(Integer rdEnabled) {
        this.rdEnabled = rdEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.rd_mail
     *
     * @return the value of cust_email.rd_mail
     *
     * @mbggenerated
     */
    public String getRdMail() {
        return rdMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.rd_mail
     *
     * @param rdMail the value for cust_email.rd_mail
     *
     * @mbggenerated
     */
    public void setRdMail(String rdMail) {
        this.rdMail = rdMail == null ? null : rdMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email1
     *
     * @return the value of cust_email.email1
     *
     * @mbggenerated
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email1
     *
     * @param email1 the value for cust_email.email1
     *
     * @mbggenerated
     */
    public void setEmail1(String email1) {
        this.email1 = email1 == null ? null : email1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email2
     *
     * @return the value of cust_email.email2
     *
     * @mbggenerated
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email2
     *
     * @param email2 the value for cust_email.email2
     *
     * @mbggenerated
     */
    public void setEmail2(String email2) {
        this.email2 = email2 == null ? null : email2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email3
     *
     * @return the value of cust_email.email3
     *
     * @mbggenerated
     */
    public String getEmail3() {
        return email3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email3
     *
     * @param email3 the value for cust_email.email3
     *
     * @mbggenerated
     */
    public void setEmail3(String email3) {
        this.email3 = email3 == null ? null : email3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email4
     *
     * @return the value of cust_email.email4
     *
     * @mbggenerated
     */
    public String getEmail4() {
        return email4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email4
     *
     * @param email4 the value for cust_email.email4
     *
     * @mbggenerated
     */
    public void setEmail4(String email4) {
        this.email4 = email4 == null ? null : email4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email5
     *
     * @return the value of cust_email.email5
     *
     * @mbggenerated
     */
    public String getEmail5() {
        return email5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email5
     *
     * @param email5 the value for cust_email.email5
     *
     * @mbggenerated
     */
    public void setEmail5(String email5) {
        this.email5 = email5 == null ? null : email5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email6
     *
     * @return the value of cust_email.email6
     *
     * @mbggenerated
     */
    public String getEmail6() {
        return email6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email6
     *
     * @param email6 the value for cust_email.email6
     *
     * @mbggenerated
     */
    public void setEmail6(String email6) {
        this.email6 = email6 == null ? null : email6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email7
     *
     * @return the value of cust_email.email7
     *
     * @mbggenerated
     */
    public String getEmail7() {
        return email7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email7
     *
     * @param email7 the value for cust_email.email7
     *
     * @mbggenerated
     */
    public void setEmail7(String email7) {
        this.email7 = email7 == null ? null : email7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cust_email.email8
     *
     * @return the value of cust_email.email8
     *
     * @mbggenerated
     */
    public String getEmail8() {
        return email8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cust_email.email8
     *
     * @param email8 the value for cust_email.email8
     *
     * @mbggenerated
     */
    public void setEmail8(String email8) {
        this.email8 = email8 == null ? null : email8.trim();
    }
}