package com.yshyerp.adm.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

@TableName("tank")
public class TankEntity implements Serializable {

    @TableField(exist = false)
    private Integer key;

    public Integer getKey() {
        return key;
    }

    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.code1
     *
     * @mbggenerated
     */
    private String code1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.d
     *
     * @mbggenerated
     */
    private String d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tank
     *
     * @mbggenerated
     */
    @TableId("tank")
    private String tank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tax
     *
     * @mbggenerated
     */
    private Boolean tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.batch_no
     *
     * @mbggenerated
     */
    @TableField("batch_no")
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t_customer
     *
     * @mbggenerated
     */
    @TableField("t_customer")
    private String tCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.c_customer
     *
     * @mbggenerated
     */
    @TableField("c_customer")
    private String cCustomer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.commodity
     *
     * @mbggenerated
     */
    private String commodity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.oil
     *
     * @mbggenerated
     */
    private Boolean oil;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.oil_o
     *
     * @mbggenerated
     */
    @TableField("oil_o")
    private Boolean oilO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tank_h
     *
     * @mbggenerated
     */
    @TableField("tank_h")
    private String tankH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.max_h
     *
     * @mbggenerated
     */
    @TableField("max_h")
    private String maxH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.max_v
     *
     * @mbggenerated
     */
    @TableField("max_v")
    private String maxV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.safety_h
     *
     * @mbggenerated
     */
    @TableField("safety_h")
    private String safetyH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.safety_v
     *
     * @mbggenerated
     */
    @TableField("safety_v")
    private String safetyV;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.klitre_cm
     *
     * @mbggenerated
     */
    @TableField("klitre_cm")
    private String klitreCm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.pipe_line
     *
     * @mbggenerated
     */
    @TableField("pipe_line")
    private String pipeLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.gauge_m
     *
     * @mbggenerated
     */
    @TableField("gauge_m")
    private BigDecimal gaugeM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.density
     *
     * @mbggenerated
     */
    private BigDecimal density;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.m_balance
     *
     * @mbggenerated
     */
    @TableField("m_balance")
    private Integer mBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.h_quan
     *
     * @mbggenerated
     */
    @TableField("h_quan")
    private Integer hQuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.lowest_vol
     *
     * @mbggenerated
     */
    @TableField("lowest_vol")
    private BigDecimal lowestVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.limit_vol
     *
     * @mbggenerated
     */
    @TableField("limit_vol")
    private BigDecimal limitVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_vol
     *
     * @mbggenerated
     */
    @TableField("crr_vol")
    private BigDecimal crrVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_vol_use
     *
     * @mbggenerated
     */
    @TableField("crr_vol_use")
    private Boolean crrVolUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.lock_tank
     *
     * @mbggenerated
     */
    @TableField("lock_tank")
    private Boolean lockTank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.phase
     *
     * @mbggenerated
     */
    private String phase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.commence
     *
     * @mbggenerated
     */
    private Date commence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.thruput_mi
     *
     * @mbggenerated
     */
    @TableField("thruput_mi")
    private Integer thruputMi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station1
     *
     * @mbggenerated
     */
    private String station1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station2
     *
     * @mbggenerated
     */
    private String station2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.station3
     *
     * @mbggenerated
     */
    private String station3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.c_status
     *
     * @mbggenerated
     */
    @TableField("c_status")
    private Boolean cStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t_use
     *
     * @mbggenerated
     */
    @TableField("t_use")
    private String tUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.last_comm
     *
     * @mbggenerated
     */
    @TableField("last_comm")
    private String lastComm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tenant
     *
     * @mbggenerated
     */
    private String tenant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.update_d
     *
     * @mbggenerated
     */
    @TableField("update_d")
    private Date updateD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crc
     *
     * @mbggenerated
     */
    private Boolean crc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crc_1
     *
     * @mbggenerated
     */
    @TableField("crc_1")
    private Boolean crc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa
     *
     * @mbggenerated
     */
    private Boolean coa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa1
     *
     * @mbggenerated
     */
    private String coa1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.coa_p
     *
     * @mbggenerated
     */
    @TableField("coa_p")
    private Short coaP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.crr_use
     *
     * @mbggenerated
     */
    @TableField("crr_use")
    private Boolean crrUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.fd
     *
     * @mbggenerated
     */
    private Boolean fd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.fd_weight
     *
     * @mbggenerated
     */
    @TableField("fd_weight")
    private BigDecimal fdWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.q1
     *
     * @mbggenerated
     */
    private Integer q1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.q2
     *
     * @mbggenerated
     */
    private Integer q2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.bs
     *
     * @mbggenerated
     */
    private Boolean bs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.g_type
     *
     * @mbggenerated
     */
    @TableField("g_type")
    private String gType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.r
     *
     * @mbggenerated
     */
    private BigDecimal r;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.t
     *
     * @mbggenerated
     */
    private Short t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.m
     *
     * @mbggenerated
     */
    private BigDecimal m;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.xfz
     *
     * @mbggenerated
     */
    private Boolean xfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.temp1
     *
     * @mbggenerated
     */
    private BigDecimal temp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.temp2
     *
     * @mbggenerated
     */
    private BigDecimal temp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.n2
     *
     * @mbggenerated
     */
    private String n2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.hot
     *
     * @mbggenerated
     */
    private Boolean hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.cool
     *
     * @mbggenerated
     */
    private Boolean cool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.tg
     *
     * @mbggenerated
     */
    private Boolean tg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.bw
     *
     * @mbggenerated
     */
    private Boolean bw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.jr
     *
     * @mbggenerated
     */
    private String jr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.hx
     *
     * @mbggenerated
     */
    private Boolean hx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.zh
     *
     * @mbggenerated
     */
    private Boolean zh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.u_date
     *
     * @mbggenerated
     */
    @TableField("u_date")
    private Date uDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tank.allow_comm
     *
     * @mbggenerated
     */
    @TableField("allow_comm")
    private String allowComm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tank
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.code
     *
     * @return the value of tank.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.code
     *
     * @param code the value for tank.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.code1
     *
     * @return the value of tank.code1
     *
     * @mbggenerated
     */
    public String getCode1() {
        return code1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.code1
     *
     * @param code1 the value for tank.code1
     *
     * @mbggenerated
     */
    public void setCode1(String code1) {
        this.code1 = code1 == null ? null : code1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.d
     *
     * @return the value of tank.d
     *
     * @mbggenerated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.d
     *
     * @param d the value for tank.d
     *
     * @mbggenerated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.tank
     *
     * @return the value of tank.tank
     *
     * @mbggenerated
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.tank
     *
     * @param tank the value for tank.tank
     *
     * @mbggenerated
     */
    public void setTank(String tank) {
        this.tank = tank == null ? null : tank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.tax
     *
     * @return the value of tank.tax
     *
     * @mbggenerated
     */
    public Boolean getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.tax
     *
     * @param tax the value for tank.tax
     *
     * @mbggenerated
     */
    public void setTax(Boolean tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.batch_no
     *
     * @return the value of tank.batch_no
     *
     * @mbggenerated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.batch_no
     *
     * @param batchNo the value for tank.batch_no
     *
     * @mbggenerated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.date
     *
     * @return the value of tank.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.date
     *
     * @param date the value for tank.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.t_customer
     *
     * @return the value of tank.t_customer
     *
     * @mbggenerated
     */
    public String gettCustomer() {
        return tCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.t_customer
     *
     * @param tCustomer the value for tank.t_customer
     *
     * @mbggenerated
     */
    public void settCustomer(String tCustomer) {
        this.tCustomer = tCustomer == null ? null : tCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.c_customer
     *
     * @return the value of tank.c_customer
     *
     * @mbggenerated
     */
    public String getcCustomer() {
        return cCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.c_customer
     *
     * @param cCustomer the value for tank.c_customer
     *
     * @mbggenerated
     */
    public void setcCustomer(String cCustomer) {
        this.cCustomer = cCustomer == null ? null : cCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.commodity
     *
     * @return the value of tank.commodity
     *
     * @mbggenerated
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.commodity
     *
     * @param commodity the value for tank.commodity
     *
     * @mbggenerated
     */
    public void setCommodity(String commodity) {
        this.commodity = commodity == null ? null : commodity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.oil
     *
     * @return the value of tank.oil
     *
     * @mbggenerated
     */
    public Boolean getOil() {
        return oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.oil
     *
     * @param oil the value for tank.oil
     *
     * @mbggenerated
     */
    public void setOil(Boolean oil) {
        this.oil = oil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.oil_o
     *
     * @return the value of tank.oil_o
     *
     * @mbggenerated
     */
    public Boolean getOilO() {
        return oilO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.oil_o
     *
     * @param oilO the value for tank.oil_o
     *
     * @mbggenerated
     */
    public void setOilO(Boolean oilO) {
        this.oilO = oilO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.tank_h
     *
     * @return the value of tank.tank_h
     *
     * @mbggenerated
     */
    public String getTankH() {
        return tankH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.tank_h
     *
     * @param tankH the value for tank.tank_h
     *
     * @mbggenerated
     */
    public void setTankH(String tankH) {
        this.tankH = tankH == null ? null : tankH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.max_h
     *
     * @return the value of tank.max_h
     *
     * @mbggenerated
     */
    public String getMaxH() {
        return maxH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.max_h
     *
     * @param maxH the value for tank.max_h
     *
     * @mbggenerated
     */
    public void setMaxH(String maxH) {
        this.maxH = maxH == null ? null : maxH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.max_v
     *
     * @return the value of tank.max_v
     *
     * @mbggenerated
     */
    public String getMaxV() {
        return maxV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.max_v
     *
     * @param maxV the value for tank.max_v
     *
     * @mbggenerated
     */
    public void setMaxV(String maxV) {
        this.maxV = maxV == null ? null : maxV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.safety_h
     *
     * @return the value of tank.safety_h
     *
     * @mbggenerated
     */
    public String getSafetyH() {
        return safetyH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.safety_h
     *
     * @param safetyH the value for tank.safety_h
     *
     * @mbggenerated
     */
    public void setSafetyH(String safetyH) {
        this.safetyH = safetyH == null ? null : safetyH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.safety_v
     *
     * @return the value of tank.safety_v
     *
     * @mbggenerated
     */
    public String getSafetyV() {
        return safetyV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.safety_v
     *
     * @param safetyV the value for tank.safety_v
     *
     * @mbggenerated
     */
    public void setSafetyV(String safetyV) {
        this.safetyV = safetyV == null ? null : safetyV.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.klitre_cm
     *
     * @return the value of tank.klitre_cm
     *
     * @mbggenerated
     */
    public String getKlitreCm() {
        return klitreCm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.klitre_cm
     *
     * @param klitreCm the value for tank.klitre_cm
     *
     * @mbggenerated
     */
    public void setKlitreCm(String klitreCm) {
        this.klitreCm = klitreCm == null ? null : klitreCm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.pipe_line
     *
     * @return the value of tank.pipe_line
     *
     * @mbggenerated
     */
    public String getPipeLine() {
        return pipeLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.pipe_line
     *
     * @param pipeLine the value for tank.pipe_line
     *
     * @mbggenerated
     */
    public void setPipeLine(String pipeLine) {
        this.pipeLine = pipeLine == null ? null : pipeLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.gauge_m
     *
     * @return the value of tank.gauge_m
     *
     * @mbggenerated
     */
    public BigDecimal getGaugeM() {
        return gaugeM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.gauge_m
     *
     * @param gaugeM the value for tank.gauge_m
     *
     * @mbggenerated
     */
    public void setGaugeM(BigDecimal gaugeM) {
        this.gaugeM = gaugeM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.density
     *
     * @return the value of tank.density
     *
     * @mbggenerated
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.density
     *
     * @param density the value for tank.density
     *
     * @mbggenerated
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.quantity
     *
     * @return the value of tank.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.quantity
     *
     * @param quantity the value for tank.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.m_balance
     *
     * @return the value of tank.m_balance
     *
     * @mbggenerated
     */
    public Integer getmBalance() {
        return mBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.m_balance
     *
     * @param mBalance the value for tank.m_balance
     *
     * @mbggenerated
     */
    public void setmBalance(Integer mBalance) {
        this.mBalance = mBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.h_quan
     *
     * @return the value of tank.h_quan
     *
     * @mbggenerated
     */
    public Integer gethQuan() {
        return hQuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.h_quan
     *
     * @param hQuan the value for tank.h_quan
     *
     * @mbggenerated
     */
    public void sethQuan(Integer hQuan) {
        this.hQuan = hQuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.lowest_vol
     *
     * @return the value of tank.lowest_vol
     *
     * @mbggenerated
     */
    public BigDecimal getLowestVol() {
        return lowestVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.lowest_vol
     *
     * @param lowestVol the value for tank.lowest_vol
     *
     * @mbggenerated
     */
    public void setLowestVol(BigDecimal lowestVol) {
        this.lowestVol = lowestVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.limit_vol
     *
     * @return the value of tank.limit_vol
     *
     * @mbggenerated
     */
    public BigDecimal getLimitVol() {
        return limitVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.limit_vol
     *
     * @param limitVol the value for tank.limit_vol
     *
     * @mbggenerated
     */
    public void setLimitVol(BigDecimal limitVol) {
        this.limitVol = limitVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.crr_vol
     *
     * @return the value of tank.crr_vol
     *
     * @mbggenerated
     */
    public BigDecimal getCrrVol() {
        return crrVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.crr_vol
     *
     * @param crrVol the value for tank.crr_vol
     *
     * @mbggenerated
     */
    public void setCrrVol(BigDecimal crrVol) {
        this.crrVol = crrVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.crr_vol_use
     *
     * @return the value of tank.crr_vol_use
     *
     * @mbggenerated
     */
    public Boolean getCrrVolUse() {
        return crrVolUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.crr_vol_use
     *
     * @param crrVolUse the value for tank.crr_vol_use
     *
     * @mbggenerated
     */
    public void setCrrVolUse(Boolean crrVolUse) {
        this.crrVolUse = crrVolUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.lock_tank
     *
     * @return the value of tank.lock_tank
     *
     * @mbggenerated
     */
    public Boolean getLockTank() {
        return lockTank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.lock_tank
     *
     * @param lockTank the value for tank.lock_tank
     *
     * @mbggenerated
     */
    public void setLockTank(Boolean lockTank) {
        this.lockTank = lockTank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.phase
     *
     * @return the value of tank.phase
     *
     * @mbggenerated
     */
    public String getPhase() {
        return phase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.phase
     *
     * @param phase the value for tank.phase
     *
     * @mbggenerated
     */
    public void setPhase(String phase) {
        this.phase = phase == null ? null : phase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.commence
     *
     * @return the value of tank.commence
     *
     * @mbggenerated
     */
    public Date getCommence() {
        return commence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.commence
     *
     * @param commence the value for tank.commence
     *
     * @mbggenerated
     */
    public void setCommence(Date commence) {
        this.commence = commence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.thruput_mi
     *
     * @return the value of tank.thruput_mi
     *
     * @mbggenerated
     */
    public Integer getThruputMi() {
        return thruputMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.thruput_mi
     *
     * @param thruputMi the value for tank.thruput_mi
     *
     * @mbggenerated
     */
    public void setThruputMi(Integer thruputMi) {
        this.thruputMi = thruputMi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.station1
     *
     * @return the value of tank.station1
     *
     * @mbggenerated
     */
    public String getStation1() {
        return station1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.station1
     *
     * @param station1 the value for tank.station1
     *
     * @mbggenerated
     */
    public void setStation1(String station1) {
        this.station1 = station1 == null ? null : station1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.station2
     *
     * @return the value of tank.station2
     *
     * @mbggenerated
     */
    public String getStation2() {
        return station2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.station2
     *
     * @param station2 the value for tank.station2
     *
     * @mbggenerated
     */
    public void setStation2(String station2) {
        this.station2 = station2 == null ? null : station2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.station3
     *
     * @return the value of tank.station3
     *
     * @mbggenerated
     */
    public String getStation3() {
        return station3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.station3
     *
     * @param station3 the value for tank.station3
     *
     * @mbggenerated
     */
    public void setStation3(String station3) {
        this.station3 = station3 == null ? null : station3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.c_status
     *
     * @return the value of tank.c_status
     *
     * @mbggenerated
     */
    public Boolean getcStatus() {
        return cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.c_status
     *
     * @param cStatus the value for tank.c_status
     *
     * @mbggenerated
     */
    public void setcStatus(Boolean cStatus) {
        this.cStatus = cStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.t_use
     *
     * @return the value of tank.t_use
     *
     * @mbggenerated
     */
    public String gettUse() {
        return tUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.t_use
     *
     * @param tUse the value for tank.t_use
     *
     * @mbggenerated
     */
    public void settUse(String tUse) {
        this.tUse = tUse == null ? null : tUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.last_comm
     *
     * @return the value of tank.last_comm
     *
     * @mbggenerated
     */
    public String getLastComm() {
        return lastComm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.last_comm
     *
     * @param lastComm the value for tank.last_comm
     *
     * @mbggenerated
     */
    public void setLastComm(String lastComm) {
        this.lastComm = lastComm == null ? null : lastComm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.tenant
     *
     * @return the value of tank.tenant
     *
     * @mbggenerated
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.tenant
     *
     * @param tenant the value for tank.tenant
     *
     * @mbggenerated
     */
    public void setTenant(String tenant) {
        this.tenant = tenant == null ? null : tenant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.update_d
     *
     * @return the value of tank.update_d
     *
     * @mbggenerated
     */
    public Date getUpdateD() {
        return updateD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.update_d
     *
     * @param updateD the value for tank.update_d
     *
     * @mbggenerated
     */
    public void setUpdateD(Date updateD) {
        this.updateD = updateD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.crc
     *
     * @return the value of tank.crc
     *
     * @mbggenerated
     */
    public Boolean getCrc() {
        return crc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.crc
     *
     * @param crc the value for tank.crc
     *
     * @mbggenerated
     */
    public void setCrc(Boolean crc) {
        this.crc = crc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.crc_1
     *
     * @return the value of tank.crc_1
     *
     * @mbggenerated
     */
    public Boolean getCrc1() {
        return crc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.crc_1
     *
     * @param crc1 the value for tank.crc_1
     *
     * @mbggenerated
     */
    public void setCrc1(Boolean crc1) {
        this.crc1 = crc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.coa
     *
     * @return the value of tank.coa
     *
     * @mbggenerated
     */
    public Boolean getCoa() {
        return coa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.coa
     *
     * @param coa the value for tank.coa
     *
     * @mbggenerated
     */
    public void setCoa(Boolean coa) {
        this.coa = coa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.coa1
     *
     * @return the value of tank.coa1
     *
     * @mbggenerated
     */
    public String getCoa1() {
        return coa1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.coa1
     *
     * @param coa1 the value for tank.coa1
     *
     * @mbggenerated
     */
    public void setCoa1(String coa1) {
        this.coa1 = coa1 == null ? null : coa1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.coa_p
     *
     * @return the value of tank.coa_p
     *
     * @mbggenerated
     */
    public Short getCoaP() {
        return coaP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.coa_p
     *
     * @param coaP the value for tank.coa_p
     *
     * @mbggenerated
     */
    public void setCoaP(Short coaP) {
        this.coaP = coaP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.crr_use
     *
     * @return the value of tank.crr_use
     *
     * @mbggenerated
     */
    public Boolean getCrrUse() {
        return crrUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.crr_use
     *
     * @param crrUse the value for tank.crr_use
     *
     * @mbggenerated
     */
    public void setCrrUse(Boolean crrUse) {
        this.crrUse = crrUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.fd
     *
     * @return the value of tank.fd
     *
     * @mbggenerated
     */
    public Boolean getFd() {
        return fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.fd
     *
     * @param fd the value for tank.fd
     *
     * @mbggenerated
     */
    public void setFd(Boolean fd) {
        this.fd = fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.fd_weight
     *
     * @return the value of tank.fd_weight
     *
     * @mbggenerated
     */
    public BigDecimal getFdWeight() {
        return fdWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.fd_weight
     *
     * @param fdWeight the value for tank.fd_weight
     *
     * @mbggenerated
     */
    public void setFdWeight(BigDecimal fdWeight) {
        this.fdWeight = fdWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.q1
     *
     * @return the value of tank.q1
     *
     * @mbggenerated
     */
    public Integer getQ1() {
        return q1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.q1
     *
     * @param q1 the value for tank.q1
     *
     * @mbggenerated
     */
    public void setQ1(Integer q1) {
        this.q1 = q1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.q2
     *
     * @return the value of tank.q2
     *
     * @mbggenerated
     */
    public Integer getQ2() {
        return q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.q2
     *
     * @param q2 the value for tank.q2
     *
     * @mbggenerated
     */
    public void setQ2(Integer q2) {
        this.q2 = q2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.bs
     *
     * @return the value of tank.bs
     *
     * @mbggenerated
     */
    public Boolean getBs() {
        return bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.bs
     *
     * @param bs the value for tank.bs
     *
     * @mbggenerated
     */
    public void setBs(Boolean bs) {
        this.bs = bs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.g_type
     *
     * @return the value of tank.g_type
     *
     * @mbggenerated
     */
    public String getgType() {
        return gType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.g_type
     *
     * @param gType the value for tank.g_type
     *
     * @mbggenerated
     */
    public void setgType(String gType) {
        this.gType = gType == null ? null : gType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.r
     *
     * @return the value of tank.r
     *
     * @mbggenerated
     */
    public BigDecimal getR() {
        return r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.r
     *
     * @param r the value for tank.r
     *
     * @mbggenerated
     */
    public void setR(BigDecimal r) {
        this.r = r;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.t
     *
     * @return the value of tank.t
     *
     * @mbggenerated
     */
    public Short getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.t
     *
     * @param t the value for tank.t
     *
     * @mbggenerated
     */
    public void setT(Short t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.m
     *
     * @return the value of tank.m
     *
     * @mbggenerated
     */
    public BigDecimal getM() {
        return m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.m
     *
     * @param m the value for tank.m
     *
     * @mbggenerated
     */
    public void setM(BigDecimal m) {
        this.m = m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.xfz
     *
     * @return the value of tank.xfz
     *
     * @mbggenerated
     */
    public Boolean getXfz() {
        return xfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.xfz
     *
     * @param xfz the value for tank.xfz
     *
     * @mbggenerated
     */
    public void setXfz(Boolean xfz) {
        this.xfz = xfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.temp1
     *
     * @return the value of tank.temp1
     *
     * @mbggenerated
     */
    public BigDecimal getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.temp1
     *
     * @param temp1 the value for tank.temp1
     *
     * @mbggenerated
     */
    public void setTemp1(BigDecimal temp1) {
        this.temp1 = temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.temp2
     *
     * @return the value of tank.temp2
     *
     * @mbggenerated
     */
    public BigDecimal getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.temp2
     *
     * @param temp2 the value for tank.temp2
     *
     * @mbggenerated
     */
    public void setTemp2(BigDecimal temp2) {
        this.temp2 = temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.n2
     *
     * @return the value of tank.n2
     *
     * @mbggenerated
     */
    public String getN2() {
        return n2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.n2
     *
     * @param n2 the value for tank.n2
     *
     * @mbggenerated
     */
    public void setN2(String n2) {
        this.n2 = n2 == null ? null : n2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.hot
     *
     * @return the value of tank.hot
     *
     * @mbggenerated
     */
    public Boolean getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.hot
     *
     * @param hot the value for tank.hot
     *
     * @mbggenerated
     */
    public void setHot(Boolean hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.cool
     *
     * @return the value of tank.cool
     *
     * @mbggenerated
     */
    public Boolean getCool() {
        return cool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.cool
     *
     * @param cool the value for tank.cool
     *
     * @mbggenerated
     */
    public void setCool(Boolean cool) {
        this.cool = cool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.tg
     *
     * @return the value of tank.tg
     *
     * @mbggenerated
     */
    public Boolean getTg() {
        return tg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.tg
     *
     * @param tg the value for tank.tg
     *
     * @mbggenerated
     */
    public void setTg(Boolean tg) {
        this.tg = tg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.bw
     *
     * @return the value of tank.bw
     *
     * @mbggenerated
     */
    public Boolean getBw() {
        return bw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.bw
     *
     * @param bw the value for tank.bw
     *
     * @mbggenerated
     */
    public void setBw(Boolean bw) {
        this.bw = bw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.jr
     *
     * @return the value of tank.jr
     *
     * @mbggenerated
     */
    public String getJr() {
        return jr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.jr
     *
     * @param jr the value for tank.jr
     *
     * @mbggenerated
     */
    public void setJr(String jr) {
        this.jr = jr == null ? null : jr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.hx
     *
     * @return the value of tank.hx
     *
     * @mbggenerated
     */
    public Boolean getHx() {
        return hx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.hx
     *
     * @param hx the value for tank.hx
     *
     * @mbggenerated
     */
    public void setHx(Boolean hx) {
        this.hx = hx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.zh
     *
     * @return the value of tank.zh
     *
     * @mbggenerated
     */
    public Boolean getZh() {
        return zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.zh
     *
     * @param zh the value for tank.zh
     *
     * @mbggenerated
     */
    public void setZh(Boolean zh) {
        this.zh = zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.u_date
     *
     * @return the value of tank.u_date
     *
     * @mbggenerated
     */
    public Date getuDate() {
        return uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.u_date
     *
     * @param uDate the value for tank.u_date
     *
     * @mbggenerated
     */
    public void setuDate(Date uDate) {
        this.uDate = uDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tank.allow_comm
     *
     * @return the value of tank.allow_comm
     *
     * @mbggenerated
     */
    public String getAllowComm() {
        return allowComm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tank.allow_comm
     *
     * @param allowComm the value for tank.allow_comm
     *
     * @mbggenerated
     */
    public void setAllowComm(String allowComm) {
        this.allowComm = allowComm == null ? null : allowComm.trim();
    }
}