package com.yshyerp.adm.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.yshyerp.adm.entity.CusEmail;

public interface CusEmailMapper extends BaseMapper<CusEmail> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cust_email
     *
     * @mbggenerated
     */
    int insertCustEmail(CusEmail record);


}